
font_list = ['AbyssinicaSIL-R.ttf', 'Sawasdee.ttf', 'Kinnari-Italic.ttf', 'Garuda-Bold.ttf', 
'TlwgTypewriter-BoldOblique.ttf', 'Kinnari-Oblique.ttf', 'Loma-Oblique.ttf', 'Laksaman-Italic.ttf', 
'Loma.ttf', 'Loma-BoldOblique.ttf', 'TlwgTypo-Bold.ttf', 'Waree-Bold.ttf', 'Purisa.ttf', 'Sawasdee-Bold.ttf', 
'Norasi-Oblique.ttf', 'Purisa-Bold.ttf', 'Umpush-BoldOblique.ttf', 'Umpush-Light.ttf', 'Purisa-Oblique.ttf', 
'TlwgMono-Bold.ttf', 'Sawasdee-Oblique.ttf', 'TlwgMono-BoldOblique.ttf', 'TlwgTypist-BoldOblique.ttf', 
'Garuda-BoldOblique.ttf', 'Norasi.ttf', 'TlwgTypewriter-Bold.ttf', 'Garuda-Oblique.ttf', 'Waree-BoldOblique.ttf', 
'Umpush-Bold.ttf', 'TlwgMono-Oblique.ttf', 'TlwgMono.ttf', 'Laksaman-Bold.ttf', 'Purisa-BoldOblique.ttf',
 'Kinnari-BoldOblique.ttf', 'Kinnari.ttf', 'TlwgTypo-Oblique.ttf', 'Kinnari-Bold.ttf', 'TlwgTypewriter.ttf', 
 'Sawasdee-BoldOblique.ttf', 'Umpush-LightOblique.ttf', 'TlwgTypewriter-Oblique.ttf', 'Waree-Oblique.ttf', 
 'Waree.ttf', 'TlwgTypist.ttf', 'Laksaman-BoldItalic.ttf', 'Laksaman.ttf', 'TlwgTypo.ttf', 'Norasi-Italic.ttf', 
 'Umpush-Oblique.ttf', 'Norasi-BoldItalic.ttf', 'Umpush.ttf', 'Kinnari-BoldItalic.ttf', 'Garuda.ttf', 
 'TlwgTypist-Oblique.ttf', 'Norasi-BoldOblique.ttf', 'Norasi-Bold.ttf', 'TlwgTypo-BoldOblique.ttf', 
 'Loma-Bold.ttf', 'TlwgTypist-Bold.ttf', 'Lato-HeavyItalic.ttf', 'Lato-Bold.ttf', 'Lato-Heavy.ttf', 
 'Lato-Semibold.ttf', 'Lato-HairlineItalic.ttf', 'Lato-Regular.ttf', 'Lato-LightItalic.ttf', 
 'Lato-Thin.ttf', 'Lato-Medium.ttf', 'Lato-SemiboldItalic.ttf', 'Lato-BlackItalic.ttf', 
 'Lato-MediumItalic.ttf', 'Lato-ThinItalic.ttf', 'Lato-Light.ttf', 'Lato-Italic.ttf', 
 'Lato-Black.ttf', 'Lato-Hairline.ttf', 'Lato-BoldItalic.ttf',  'Caladea-Bold.ttf', 
 'Carlito-BoldItalic.ttf', 'Carlito-Regular.ttf', 'Caladea-Italic.ttf', 'Caladea-BoldItalic.ttf',
  'Carlito-Bold.ttf', 'Caladea-Regular.ttf', 'Carlito-Italic.ttf', 'Rachana-Bold.ttf',
  'Chilanka-Regular.ttf', 'Dyuthi.ttf', 'Suruma.ttf', 'Rachana-Regular.ttf', 'Meera.ttf', 'Keraleeyam.ttf', 
  'AnjaliOldLipi.ttf', 'Uroob.ttf', 'Karumbi.ttf', 'GenBkBasBI.ttf', 
  'GenBkBasB.ttf', 'GenBkBasI.ttf', 'GenBasR.ttf', 'GenBkBasR.ttf', 'GenBasB.ttf', 'GenBasBI.ttf',
   'GenBasI.ttf', 'UbuntuMono-BI.ttf', 'Ubuntu-B.ttf', 'Ubuntu-LI.ttf', 'UbuntuMono-RI.ttf', 
   'Ubuntu-M.ttf', 'UbuntuMono-B.ttf', 'Ubuntu-C.ttf', 'Ubuntu-R.ttf', 'Ubuntu-L.ttf', 'Ubuntu-MI.ttf', 
   'Ubuntu-RI.ttf', 'Ubuntu-BI.ttf', 'UbuntuMono-R.ttf', 'LiberationSansNarrow-BoldItalic.ttf', 
   'LiberationMono-Regular.ttf', 'LiberationSerif-BoldItalic.ttf', 'LiberationSansNarrow-Regular.ttf', 
   'LiberationSerif-Italic.ttf', 'LiberationSans-BoldItalic.ttf', 'LiberationMono-BoldItalic.ttf', 
   'LiberationSans-Regular.ttf', 'LiberationSerif-Bold.ttf', 'LiberationSansNarrow-Italic.ttf', 
   'LiberationSans-Italic.ttf', 'LiberationMono-Italic.ttf', 'LiberationSans-Bold.ttf', 'LiberationSerif-Regular.ttf', 
   'LiberationMono-Bold.ttf', 'LiberationSansNarrow-Bold.ttf', 'NotoMono-Regular.ttf', 'OpenSans-Semibold.ttf', 
   'OpenSans-Regular.ttf', 'OpenSans-ExtraBoldItalic.ttf', 'OpenSans-Light.ttf', 'OpenSans-SemiboldItalic.ttf', 
   'OpenSans-Bold.ttf', 'OpenSans-BoldItalic.ttf', 'OpenSans-CondLightItalic.ttf', 'OpenSans-ExtraBold.ttf', 
   'OpenSans-LightItalic.ttf', 'OpenSans-CondBold.ttf', 'OpenSans-CondLight.ttf', 'OpenSans-Italic.ttf', 
   'FreeMonoOblique.ttf', 'FreeMonoBold.ttf', 'FreeSerifBold.ttf', 'FreeMono.ttf', 'FreeSerifBoldItalic.ttf', 
   'FreeSerifItalic.ttf', 'FreeSansOblique.ttf', 'FreeSerif.ttf', 'FreeSansBold.ttf', 'FreeSans.ttf', 
   'FreeSansBoldOblique.ttf', 'FreeMonoBoldOblique.ttf', 'sahadeva.ttf', 'Pagul.ttf', 'PadaukBook-Regular.ttf', 
   'Padauk-Regular.ttf', 'Padauk-Bold.ttf', 'PadaukBook-Bold.ttf', 
   'Gentium-I.ttf', 'GentiumAlt-I.ttf', 'GentiumAlt-R.ttf', 'Gentium-R.ttf', 'Phetsarath_OT.ttf', 
   'JamrulNormal.ttf','mitra.ttf', 'MuktiNarrow.ttf', 'ani.ttf', 'LikhanNormal.ttf', 'MuktiNarrowBold.ttf', 
   'kalimati.ttf', 'samanata.ttf', 'chandas1-2.ttf', 
    'KhmerOS.ttf', 'KhmerOSsys.ttf', 'DejaVuSerifCondensed-Bold.ttf', 'DejaVuMathTeXGyre.ttf', 
    'DejaVuSerifCondensed-BoldItalic.ttf', 'DejaVuSansMono-Bold.ttf', 'DejaVuSerifCondensed.ttf', 'DejaVuSansMono.ttf',
     'DejaVuSerif.ttf', 'DejaVuSans-BoldOblique.ttf', 'DejaVuSerif-BoldItalic.ttf', 'DejaVuSans-ExtraLight.ttf', 
     'DejaVuSans-Oblique.ttf', 'DejaVuSansMono-BoldOblique.ttf', 'DejaVuSansCondensed-Oblique.ttf', 
     'DejaVuSerifCondensed-Italic.ttf', 'DejaVuSans.ttf', 'DejaVuSansMono-Oblique.ttf', 'DejaVuSansCondensed-Bold.ttf', 
     'DejaVuSansCondensed-BoldOblique.ttf', 'DejaVuSans-Bold.ttf', 'DejaVuSerif-Italic.ttf', 'DejaVuSerif-Bold.ttf', 
     'DejaVuSansCondensed.ttf', 'Gargi.ttf', 'Sarai.ttf', 'nakula.ttf',  
     'LiberationMono-Regular.ttf', 'LiberationSerif-BoldItalic.ttf', 'LiberationSerif-Italic.ttf', 
     'LiberationSans-BoldItalic.ttf', 'LiberationMono-BoldItalic.ttf', 'LiberationSans-Regular.ttf', 'LiberationSerif-Bold.ttf', 
     'LiberationSans-Italic.ttf', 'LiberationMono-Italic.ttf', 'LiberationSans-Bold.ttf', 'LiberationSerif-Regular.ttf', 
     'LiberationMono-Bold.ttf', 'TibetanMachineUni.ttf', 'Manjari-Thin.otf', 'Manjari-Bold.otf', 'Manjari-Regular.otf', 
    'LinBiolinum_RB.otf', 'LinBiolinum_R.otf', 'NotoSerifCJK-Bold.ttc', 'NotoSerifCJK-Regular.ttc', 
     'NotoSansCJK-Regular.ttc', 'NotoSansCJK-Bold.ttc', 'Cantarell-Bold.otf', 'Cantarell-Regular.otf', 'Cantarell-BoldOblique.otf', 
     'Cantarell-Oblique.otf']